### ISSUE TITLE
串口通讯要求

### ISSUE THREAD

**Issue by jiangsl1303** [guohaomeng/JY-ME01#1]
这个只能搭配维特官方上位机使用吗。直接连uno板子可以读取数据不

**Comment by guohaomeng** [comment]
不用上位机就能用，程序按照`modbus_test.cpp`里写就能把数据读到单片机里，不过你得设置好波特率单片机才能跟传感器通信

上位机跟说明书都是顺手放上去的，省的以后找资料麻烦🤣

**Comment by jiangsl1303** [comment]
在使用库的时候遇到了一些bug，大佬方便加个联系方式吗，我发截图看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月18日(周二) 上午10:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guohaomeng/JY-ME01] 串口通讯要求 (Issue #1)




 
不用上位机就能用，程序按照modbus_test.cpp里写就能把数据读到单片机里，不过你得设置好波特率单片机才能跟传感器通信
 
上位机跟说明书都是顺手放上去的，省的以后找资料麻烦🤣

**Comment by guohaomeng** [comment]
不是大佬😂你还是用图床贴到issues里吧，这样别人碰到一样的问题也能看到

[https://postimages.org/](https://postimages.org/)

**Comment by jiangsl1303** [comment]
> 不是大佬😂你还是用图床贴到issues里吧，这样别人碰到一样的问题也能看到
> 
> https://postimages.org/

https://i.postimg.cc/t4Cw2QTv/ZESMFM-6-XYD-D-7-8-XNCV3-G.png我用的UNOR3板子，编译不了，报错信息如图 。
PS:刚入门小白，还在慢慢摸索学习=……=

**Comment by guohaomeng** [comment]
我看到你的图了，这个是没有找到库文件造成的，先使用`Ctrl`+`K`打开项目文件夹，然后把angle_sensor文件夹复制进去就能使用了。
[![image.png](https://i.postimg.cc/N0SbwZx4/image.png)](https://postimg.cc/4Kvp6Lq7)

但我看你使用的是`Arduino UNO`开发板，这块开发板只有一个串口，开发板跟电脑通讯时需要占用一个串口，所以没有多余的串口连接传感器了，真要使用的话还是换个开发板吧，比如ESP32开发板，兼容Arduino代码，性能比Arduino强多了，而且有三个串口

**Comment by jiangsl1303** [comment]
> 

https://i.postimg.cc/nV3rcm5X/ENWE14-MU6-BEK-R-71-YU3-E.png
把库放进去，我换了mega2560板子编译了一下。报错情况如上，2560上有三套RXTX串口应该可以满足使用吧

**Comment by guohaomeng** [comment]
看不清图呀，上传完图片直接把这个markdown格式的链接粘贴过来就行了
[![image.png](https://i.postimg.cc/8cwB5Cvh/image.png)](https://postimg.cc/q6hCD4jR)
像这样贴到评论框里发送：

```md
文字文字文字，图片另起一行

[![image.png](https://i.postimg.cc/8cwB5Cvh/image.png)](https://postimg.cc/q6hCD4jR)
```

**Comment by guohaomeng** [comment]
我这个程序只在ESP32上做过验证，然后传感器就线断坏了，其他板子肯定会有些小bug，不过应该都能很简单解决

**Comment by jiangsl1303** [comment]
> 看不清图呀，上传完图片直接把这个markdown格式的链接粘贴过来就行了 [![image.png](https://camo.githubusercontent.com/3c270450d6c744048fc583f5866e70e0b8ddc5f02c8f4e3f5c528bf84ac61fbe/68747470733a2f2f692e706f7374696d672e63632f38637742354376682f696d6167652e706e67)](https://postimg.cc/q6hCD4jR) 像这样贴到评论框里发送：
> 
> ```lisp
> 文字文字文字，图片另起一行
> 
> [![image.png](https://i.postimg.cc/8cwB5Cvh/image.png)](https://postimg.cc/q6hCD4jR)
> ```

[![ENWE14-MU6-BEK-R-71-YU3-E.png](https://i.postimg.cc/nV3rcm5X/ENWE14-MU6-BEK-R-71-YU3-E.png)](https://postimg.cc/5jFbsXfJ)
抱歉抱歉第一次用这个图床，我重新传了一张应该清晰多了

**Comment by guohaomeng** [comment]
这个看样子是因为库里用到了几个Arduino没有原生支持的函数造成的，像`vTaskDelay()`、`printf()`这两个函数在`esp32`开发板上有，`uno`跟`mega2560`开发板都没有，所以才报错的，你再试试新分支`mega2560`下的代码，我之前改了改，应该能编译通过

[![image.png](https://i.postimg.cc/0QqV7VCk/image.png)](https://postimg.cc/1gJ0QcT2)

**Comment by jiangsl1303** [comment]
[![YW-SS-7-L-MDA-X4-PV05-CN.png](https://i.postimg.cc/15mPSHwN/YW-SS-7-L-MDA-X4-PV05-CN.png)](https://postimg.cc/s1Nb95nV)
哇，换了新的库之后报错果然少很多了，只剩printf还是提示缺少

**Comment by jiangsl1303** [comment]
我尝试加了个printf的注释库，但是报错更多了2333，应该是注释不完全相同

**Comment by jiangsl1303** [comment]
我漏改了主程序⊙﹏⊙。现在编译通过了大佬，恰个微信给你买瓶红牛，感谢感谢

**Comment by guohaomeng** [comment]
哈哈，不必啦，你能成功就好~

有问题欢迎再开issues提问😉
